# Generated by Django 5.0 on 2026-03-19 03:51

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_color_user_bio_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Worker/Collector',
                'verbose_name_plural': 'Workers/Collectors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('company', 'Company'), ('worker', 'Worker/Collector'), ('admin', 'Admin')], default='regular', max_length=20),
        ),
    ]
