# Generated by Django 5.0 on 2026-03-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetype',
            name='icon',
            field=models.CharField(default='♻️', max_length=10),
        ),
        migrations.CreateModel(
            name='CollectedWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('waste_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='companies.wastetype')),
            ],
            options={
                'verbose_name': 'Collected Waste Inventory',
                'verbose_name_plural': 'Collected Waste Inventory',
            },
        ),
    ]
