# Generated by Django 5.0 on 2026-03-19 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_company',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='pickups/qr/'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='waste_category',
            field=models.CharField(blank=True, choices=[('recyclable', 'Recyclable'), ('non_recyclable', 'Non-Recyclable'), ('hazardous', 'Hazardous'), ('organic', 'Organic'), ('electronic', 'Electronic (E-Waste)')], max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='waste_image',
            field=models.ImageField(blank=True, null=True, upload_to='pickups/images/'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL),
        ),
    ]
